eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  profiles:
    active: test